/* Priority 10 visual simulation. Real authorization and persistence live in ASP.NET Core. */
function createSelfServicePreview(ctx) {
  const {store, escapeHtml:e, header, table, button:b, showForm, amount, idFor, today, save, render, toast, download, closeDrawer} = ctx;
  const user=()=>ctx.account(), dealer=()=>store.dealers[0], manager=()=>['sales.manager','channel.manager'].includes(user());
  const kinds={Order:'درخواست سفارش',Lead:'ثبت سرنخ',Complaint:'شکایت',Claim:'ادعای خسارت',AccessInvite:'کاربر جدید',AccessRevoke:'لغو دسترسی'};
  const states={Submitted:'ثبت‌شده',InReview:'در حال بررسی',Accepted:'تأییدشده',Rejected:'ردشده',Cancelled:'لغوشده'};
  const visitStates={Planned:'برنامه‌ریزی‌شده',CheckedIn:'در حال بازدید',Completed:'انجام‌شده',Cancelled:'لغوشده'};
  const products=[{code:'PRD-1001',name:'محصول نمونه ۱',price:850000000,available:20},{code:'PRD-1002',name:'محصول نمونه ۲',price:1250000000,available:15}];
  store.portalRequests ??= [{id:101,dealerId:81,owner:'dealer.user',kind:'Complaint',subject:'پیگیری زمان تحویل',description:'لطفاً زمان تحویل محمولهٔ آزمایشی اعلام شود.',status:'Submitted',reply:'',version:1,created:today}];
  store.portalAccounts ??= [{id:1,name:'کاربر نماینده',username:'dealer.user',status:'فعال'}];
  store.visits ??= [{id:111,owner:'sales.manager',customerId:store.customers[0].id,customer:store.customers[0].name,branch:store.customers[0].branch,planned:today+'T08:00',purpose:'بررسی نیاز و پیگیری همکاری',status:'Planned',version:1,outcome:'',synced:''}];
  const ownRequests=()=>store.portalRequests.filter(x=>x.dealerId===dealer()?.id);
  const myVisits=()=>store.visits.filter(x=>x.owner===user()&&ctx.visible(x));
  const customerOptions=()=>store.customers.filter(x=>dealer()?.customers.includes(x.id));
  const field=(label,name,value='',type='text')=>`<label>${label}<input name="${name}" type="${type}" value="${e(value)}" required maxlength="2000"></label>`;
  const select=(label,name,entries)=>`<label>${label}<select name="${name}">${entries.map(([v,t])=>`<option value="${e(v)}">${e(t)}</option>`).join('')}</select></label>`;
  let offline=false, queue=[], lastSync='', blocked=false, token=0;
  const allowed=route=>route==='portal'?user()==='dealer.user':route==='partner-requests'?manager():route==='mobile'?['sales.manager','sales.expert'].includes(user()):user()!=='dealer.user';
  function portalView(){const d=dealer();return header('پرتال نماینده',e(d?.name||'نماینده نمونه'),b('p10-request','ثبت درخواست'))+
    `<section class="u-grid"><article class="u-card"><span>ماندهٔ حساب نمایندگی</span><strong>${amount(3980000000)} ریال</strong><small>سررسید گذشته: ${amount(620000000)} · ERP نمونه</small></article><article class="u-card"><span>هدف دوره</span><strong>${amount(d?.target)} ریال</strong><small>عملکرد همان دوره: ${amount(d?.actual)}</small></article><article class="u-card"><span>درخواست‌های باز</span><strong>${ownRequests().filter(x=>['Submitted','InReview'].includes(x.status)).length}</strong><small>ثبت درخواست، تأیید سفارش قطعی نیست.</small></article></section>`+
    `<section class="panel u-panel"><h2>کالا، قیمت و موجودی مجاز</h2>${table(['کالا','قیمت پایه / ریال','موجودی'],products.map(p=>`<tr><td>${p.name}<small class="cell-sub">${p.code}</small></td><td>${amount(p.price)}</td><td>${p.available}</td></tr>`).join(''))}<p class="u-period">منبع: ERP نمونه · تاریخ نمونه: ${today} · بدون تخفیف کمپین · موجودی رزرو نمی‌شود.</p></section>`+
    `<section class="panel u-panel"><h2>درخواست‌ها و پاسخ‌ها</h2>${table(['عنوان','نوع','وضعیت','پاسخ','عملیات'],ownRequests().slice().reverse().map(r=>`<tr><td>${e(r.subject)}<small class="cell-sub">PR-${r.id}</small></td><td>${kinds[r.kind]}</td><td>${states[r.status]}${r.protectedUntil?'<small class="cell-sub">حفاظت تا '+e(r.protectedUntil)+'</small>':''}</td><td>${e(r.reply||'در انتظار بررسی')}${r.orderId?'<small class="cell-sub">سفارش: '+e(store.orders.find(o=>o.id===r.orderId)?.status||'—')+'</small>':''}</td><td>${['Submitted','InReview'].includes(r.status)?b('p10-cancel','لغو',r.id):''}</td></tr>`).join(''))}</section>`+
    `<section class="panel u-panel"><h2>صورتحساب و کاربران نمایندگی</h2><p>فاکتور DEMO-1405-001 · مبلغ ${amount(1200000000)} ریال · وصول‌شده ${amount(580000000)}</p>${b('p10-invoice','دریافت صورتحساب نمونه CSV')}<h3>کاربران</h3>${store.portalAccounts.map(a=>`<p>${e(a.name)} · ${e(a.username)} · ${e(a.status)}</p>`).join('')}<p class="u-period">دعوت کاربر، درخواست بررسی است؛ پیام واقعی ارسال نمی‌شود.</p></section>`;}
  function inboxView(){return header('درخواست‌های نمایندگان','رسیدگی داخلی؛ پاسخ برای نماینده نمایش داده می‌شود.')+`<section class="panel u-panel">${table(['عنوان','نماینده','نوع','وضعیت','عملیات'],store.portalRequests.filter(x=>dealer()?.id===x.dealerId&&ctx.visible(dealer())).map(r=>`<tr><td>${e(r.subject)}</td><td>${e(dealer().name)}</td><td>${kinds[r.kind]}</td><td>${states[r.status]}</td><td>${b('p10-review','بررسی',r.id)}</td></tr>`).join(''))}</section>`;}
  function shownVisit(v){return queue.filter(x=>x.id===v.id).reduce((a,x)=>({...a,status:x.status,version:a.version+1,outcome:x.outcome}),v);}
  function mobileView(){return header('بازدیدهای من','برنامهٔ بازدید، ثبت شروع و نتیجه',b('p10-plan','برنامه‌ریزی بازدید'))+
    `<section class="panel u-panel"><h2>${offline?'حالت آفلاین نمایشی':'حالت متصل نمایشی'}</h2><p>صف: ${queue.length} عملیات · آخرین ارسال: ${e(lastSync||'هنوز انجام نشده')}${blocked?' · تعارض نیازمند بررسی':''}</p><div class="u-actions">${b('p10-offline',offline?'اتصال دوباره':'شبیه‌سازی قطع ارتباط')}${b('p10-sync','ارسال صف')}${b('p10-discard','حذف صف')}</div><p class="u-period">این فایل سرور ندارد؛ ارسال، تغییر دادهٔ نمونه است. صف فقط در حافظهٔ همین صفحه می‌ماند و با خروج یا بستن صفحه از بین می‌رود. حداکثر ۵۰ عملیات / ۸ ساعت.</p></section>`+
    `<section class="u-grid">${myVisits().map(original=>{const v=shownVisit(original);return `<article class="u-card"><span>${e(v.customer)}</span><strong>${visitStates[v.status]}</strong><small>${e(v.planned)} UTC · ${e(v.purpose)}</small><p>${e(v.outcome)}</p><small>نسخه ${v.version}${queue.some(x=>x.id===v.id)?' · در صف ارسال':''}</small><div class="u-actions">${v.status==='Planned'?b('p10-checkin','شروع',v.id)+b('p10-visitcancel','لغو',v.id):v.status==='CheckedIn'?b('p10-complete','پایان و نتیجه',v.id):''}</div></article>`;}).join('')||'<p>بازدیدی ندارید؛ برنامهٔ جدید ثبت کنید.</p>'}</section>`;}
  function fail(text){toast(text,'warning');return true;}
  function expire(){if(queue.some(x=>Date.now()-x.at>=28800000)){queue=[];blocked=true;throw new Error('صف منقضی پاک شد؛ دادهٔ سرور را دوباره بررسی کنید.');}}
  function sync(){expire();if(offline)return fail('ابتدا اتصال نمایشی را برقرار کنید.');if(blocked)return fail('صف متعارض را بررسی و سپس حذف کنید.');while(queue.length){const q=queue[0],v=myVisits().find(x=>x.id===q.id);if(!v||v.version!==q.version){blocked=true;return fail('تعارض نسخه؛ هیچ بازنویسی خودکاری انجام نشد.');}Object.assign(v,{status:q.status,outcome:q.outcome,version:v.version+1,synced:new Date().toISOString()});queue.shift();save();}lastSync=new Date().toLocaleString('fa-IR');render();return true;}
  function action(action,id){if(!action.startsWith('p10-'))return false;
    if(['p10-offline','p10-sync','p10-discard','p10-plan','p10-checkin','p10-complete','p10-visitcancel'].includes(action)&&!allowed('mobile'))return fail('این صفحه برای نقش شما فعال نیست.');
    if(action==='p10-request'){if(!allowed('portal')||dealer().status!=='فعال')return fail('نماینده فعال لازم است.');showForm('ثبت درخواست نماینده',select('نوع','kind',Object.entries(kinds))+field('عنوان / نام کاربر','subject')+field('شرح / اطلاعات پیگیری','description')+select('مشتری سفارش','customerId',customerOptions().map(x=>[x.id,x.name]))+select('کالا','productCode',products.map(x=>[x.code,x.name]))+field('تعداد','quantity',1,'number')+`<label>ایمیل برای دعوت<input name="email" type="email" maxlength="256"></label>`+select('کاربر برای لغو دسترسی','targetUserId',store.portalAccounts.filter(x=>x.username!==user()&&x.status!=='لغوشده').map(x=>[x.id,x.name])),'p10-request');return true;}
    if(action==='p10-invoice'){if(allowed('portal'))download('dealer-invoice-demo.csv','\ufeffNumber,Total,Collected,Source\r\nDEMO-1405-001,1200000000,580000000,Demo ERP','text/csv;charset=utf-8');return true;}
    if(action==='p10-cancel'){const r=ownRequests().find(x=>x.id===Number(id));if(allowed('portal')&&r&&['Submitted','InReview'].includes(r.status)){r.status='Cancelled';r.version++;save();render();}return true;}
    if(action==='p10-review'){const r=store.portalRequests.find(x=>x.id===Number(id));if(!manager()||!r||!ctx.visible(dealer()))return true;if(!['Submitted','InReview'].includes(r.status))return fail('درخواست نهایی شده است.');showForm('بررسی '+r.subject,`<p>${e(r.description)}</p><p>${e(r.email||'')}</p><input name="version" type="hidden" value="${r.version}">`+select('تصمیم','status',[['InReview','در حال بررسی'],['Accepted','تأیید'],['Rejected','رد']])+field('پاسخ برای نماینده','reply')+`<label>شناسه عددی سفارش برای تأیید سفارش<input name="orderId" type="number"></label><p>سفارش باید پیش‌تر در گردش پیش‌فاکتور و اعتبار ساخته شده باشد.</p>`,'p10-review',r.id);return true;}
    if(action==='p10-plan'){if(offline)return fail('برنامه‌ریزی بازدید به اتصال نیاز دارد.');showForm('برنامه‌ریزی بازدید',select('مشتری','customerId',store.customers.filter(ctx.visible).map(x=>[x.id,x.name]))+field('زمان UTC','planned',today+'T08:00','datetime-local')+field('هدف','purpose'),'p10-plan');return true;}
    if(['p10-checkin','p10-complete','p10-visitcancel'].includes(action)){const v=myVisits().find(x=>x.id===Number(id));if(!v)return true;const current=shownVisit(v),next=action==='p10-checkin'?'CheckedIn':action==='p10-complete'?'Completed':'Cancelled';if(!(current.status==='Planned'&&['CheckedIn','Cancelled'].includes(next)||current.status==='CheckedIn'&&next==='Completed'))return fail('انتقال وضعیت مجاز نیست.');showForm(visitStates[next],`<input name="version" type="hidden" value="${current.version}"><input name="status" type="hidden" value="${next}">`+field('یادداشت / نتیجه','outcome')+'<p>این فایل موقعیت واقعی دریافت نمی‌کند؛ دریافت موقعیت اختیاری با رضایت در پروژه MVC وجود دارد.</p>','p10-visit',id);return true;}
    if(action==='p10-offline'){offline=!offline;render();return true;}if(action==='p10-sync'){try{return sync();}catch(e){render();return fail(e.message);}}
    if(action==='p10-discard'){queue=[];blocked=false;render();return true;}return true;
  }
  function submit(kind,data,id){if(!kind.startsWith('p10-'))return false;
    const required=(s,n)=>{if(!s?.trim()||s.length>n)throw new Error('فیلدهای الزامی و محدودیت طول را بررسی کنید.');return s.trim();};
    if(kind==='p10-request'){if(!allowed('portal')||dealer().status!=='فعال')throw new Error('ثبت درخواست مجاز نیست.');const r={id:idFor('portalRequests'),dealerId:dealer().id,owner:user(),kind:data.kind,subject:required(data.subject,160),description:required(data.description,2000),status:'Submitted',version:1,created:today,reply:''};if(!kinds[r.kind])throw new Error('نوع نامعتبر است.');if(r.kind==='Order'){const c=customerOptions().find(x=>x.id===Number(data.customerId)),p=products.find(x=>x.code===data.productCode),qty=Number(data.quantity);if(!c||!p||!Number.isFinite(qty)||qty<=0||qty>10000)throw new Error('مشتری، کالا یا تعداد نامعتبر است.');Object.assign(r,{customerId:c.id,product:p.code,quantity:qty,unitPrice:p.price});}if(r.kind==='AccessInvite'){if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(data.email||''))throw new Error('ایمیل دعوت لازم است.');r.email=data.email;}if(r.kind==='AccessRevoke'){const target=store.portalAccounts.find(x=>x.id===Number(data.targetUserId)&&x.username!==user()&&x.status!=='لغوشده');if(!target)throw new Error('حساب مجاز انتخاب کنید.');r.targetUserId=target.id;}store.portalRequests.push(r);}
    if(kind==='p10-review'){const r=store.portalRequests.find(x=>x.id===Number(id));if(!manager()||!r||!ctx.visible(dealer()))throw new Error('دسترسی معتبر نیست.');if(r.version!==Number(data.version)||!['Submitted','InReview'].includes(r.status))throw new Error('نسخهٔ درخواست تغییر کرده است.');const reply=required(data.reply,2000);if(!['Accepted','Rejected','InReview'].includes(data.status))throw new Error('تصمیم معتبر نیست.');if(data.status==='Accepted'){if(r.kind==='Order'){const order=store.orders.find(o=>o.id===Number(data.orderId)&&o.customer===store.customers.find(c=>c.id===r.customerId)?.name&&ctx.visible(o));if(!order||store.portalRequests.some(x=>x.orderId===order.id))throw new Error('سفارش مجازِ همین مشتری انتخاب کنید.');r.orderId=order.id;}if(r.kind==='Lead'){if(user()!=='sales.manager')throw new Error('ایجاد سرنخ نیازمند مدیر فروش است.');if(store.portalRequests.some(x=>x.kind==='Lead'&&x.protectedUntil>today&&x.subject===r.subject))throw new Error('تداخل حفاظت سرنخ باید بررسی شود.');const lid=idFor('leads');store.leads.push({id:lid,name:r.subject,contact:'پرتال نماینده',source:'DealerPortal',owner:'مدیر فروش',branch:dealer().branch,status:'جدید',score:50,sla:'در انتظار',created:today});r.leadId=lid;r.protectedUntil=new Date(Date.now()+30*86400000).toISOString().slice(0,10);}if(['AccessInvite','AccessRevoke'].includes(r.kind)){if(user()!=='sales.manager')throw new Error('مدیر دسترسی باید تأیید کند.');if(r.kind==='AccessInvite'){if(store.portalAccounts.some(x=>x.email===r.email))throw new Error('حساب موجود نیاز به بررسی دارد.');store.portalAccounts.push({id:idFor('portalAccounts'),name:r.subject,username:'dealer.demo.'+r.id,email:r.email,status:'در انتظار فعال‌سازی'});}else{const target=store.portalAccounts.find(x=>x.id===r.targetUserId&&x.username!=='dealer.user');if(!target)throw new Error('حساب معتبر نیست.');target.status='لغوشده';}}}Object.assign(r,{status:data.status,reply,version:r.version+1});}
    if(kind==='p10-plan'){if(!allowed('mobile')||offline)throw new Error('برنامه‌ریزی فقط آنلاین است.');const c=store.customers.find(x=>x.id===Number(data.customerId)&&ctx.visible(x));if(!c||!Number.isFinite(Date.parse(data.planned)))throw new Error('مشتری یا زمان معتبر نیست.');store.visits.push({id:idFor('visits'),owner:user(),customerId:c.id,customer:c.name,branch:c.branch,planned:data.planned,purpose:required(data.purpose,1000),status:'Planned',version:1,outcome:''});}
    if(kind==='p10-visit'){expire();if(!allowed('mobile')||blocked||queue.length>=50)throw new Error('صف یا دسترسی قابل استفاده نیست.');const v=myVisits().find(x=>x.id===Number(id)),s=v&&shownVisit(v);if(!s||s.version!==Number(data.version)||!(s.status==='Planned'&&['CheckedIn','Cancelled'].includes(data.status)||s.status==='CheckedIn'&&data.status==='Completed'))throw new Error('نسخه یا وضعیت بازدید تغییر کرده است.');queue.push({key:++token,id:v.id,version:s.version,status:data.status,outcome:required(data.outcome,2000),at:Date.now()});if(!offline)sync();}
    save();closeDrawer();render();toast('تغییر در مدل نمونه ثبت شد.');return true;
  }
  return {allowed,views:{portal:portalView,'partner-requests':inboxView,mobile:mobileView},action,submit,reset(){queue=[];offline=false;blocked=false;lastSync='';},pending:()=>queue.length,tick(){try{expire();}catch(error){toast(error.message,'warning');render();}}};
}
